name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install

      - run: pnpm run build

      - run: pnpm run test

      - run: cd example && pnpm install && pnpm run build && pnpm run test
